on: [push, pull_request]
name: Continuous Integration Build and Test

jobs:
  build:
    name: Build
    timeout-minutes: 60
    strategy:
      # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: 'Linux'
            platform:  'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'Windows'
            platform:  'windows/amd64'
            os: 'windows-latest'
          - name: 'MacOS'
            platform:  'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install .NET 10.0
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Build
        run: |
          dotnet build ManagedMidi.slnx
          dotnet test ManagedMidi.slnx

      - name: Pack 
        run: nuget pack ManagedMidi.slnx
